### PR TITLE
Added Rayman 2 compabitility

### PR DESCRIPTION
**Pull request by katas94**
Hey, I made dinputto8 compatible with "Rayman 2: The Great Escape". Rayman 2 has a known bug that requires input devices to be enumerated in a specific order, this makes the game to not recognise gamepads in modern systems. This was fixed 8 years ago by wrapping the dinput API and sorting the input devices before returning them to the game. This fix is crashing in some systems (like mine), but your dinput wrapper is up to date and can serve for the same purpose by adding the simple sorting code.

I am not a C++ developer, I have some basic knowledge, just enough to copy the code from the old project and make it work, but I don't really know if this code could impact on the current dinputto8 features, it shouldn't since as far as I know, it is just a reordering of the returned input devices.

Would be awesome to have this second alternative to the old fix, and also taking the advantages of the dinput8 capabilities (Don't really know if that would apply to Rayman 2).

For more context on how I came up with this solution you can go [here](https://raymanpc.com/forum/viewtopic.php?f=89&t=74489).

Old dinput.dll wrapper project with the extracted code can be found [here](https://code.google.com/archive/p/noser-sandbox/source/default/source). Download the zip file and open just the Rayman2InputFix project.

Thank you for this awesome project!

### CODE REVIEW

**Comment by RibShark** [comment]
That is not the bug in Rayman 2. The bug in Rayman 2 is that it stops enumerating when it encounters a device other than KB/M or Joystick. This happens to fix it by coincidence only. Regardless, I am not sure that game-specific fixes belong in this repo.

**Comment by katas94** [comment]
> That is not the bug in Rayman 2. The bug in Rayman 2 is that it stops enumerating when it encounters a device other than KB/M or Joystick. This happens to fix it by coincidence only. Regardless, I am not sure that game-specific fixes belong in this repo.

Probably right, thanks for the call!

**Comment by elishacloud** [comment]
@katas94, first of all, thanks for the pull request.  This code just changes the order of devices returned and the order of devices returned are not guaranteed by Windows, so this update should be generic and work for all games.  Also, one of the goals of this project is to fix compatibility issues with older games, so this request fits with the goals of this project.

However, there were a few issues with the pull request:
1. It updated only the ASCII interface version 1.  These specific interfaces should not be updated independently.  Instead the code should be in the 'X' interface (`IDirectInputX.cpp`).
2. I don't use `OutputDebugStringA()` for debug logs.  Instead, I updated it to use `Logging::Log()`

**Comment by katas94** [comment]
Thank you @elishacloud!, I compiled the current HEAD and confirmed that Rayman 2 is still working ^^. Are you planning to release soon ?

**Pull request merged**
